joint_names: ["sdh_knuckle_joint", "sdh_thumb_2_joint", "sdh_thumb_3_joint", "sdh_finger_12_joint", "sdh_finger_13_joint", "sdh_finger_22_joint", "sdh_finger_23_joint"]

# press button
button: [[0.0, 0.0, -1.57, -1.57, 0.0, -1.57, 0.0]]
